@LibraryBookBorrowingSystem_HostAddress = http://localhost:5121

GET {{LibraryBookBorrowingSystem_HostAddress}}/api/books
Accept: application/json

###

GET {{LibraryBookBorrowingSystem_HostAddress}}/api/members
Accept: application/json

###

GET {{LibraryBookBorrowingSystem_HostAddress}}/api/borrows
Accept: application/json

###
